### ISSUE TITLE
ConvexPolygon2D throws an OutdatedPolygonException even when both polygons are first updated

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/euclid#43]
```
Exception in thread "GDXFootstepPlanGraphic-pool-28346-thread-5" us.ihmc.euclid.geometry.exceptions.OutdatedPolygonException: Call the update method before doing any other calculation!
	at us.ihmc.euclid.geometry.interfaces.ConvexPolygon2DReadOnly.checkIfUpToDate(ConvexPolygon2DReadOnly.java:57)
	at us.ihmc.euclid.geometry.interfaces.ConvexPolygon2DReadOnly.getVertex(ConvexPolygon2DReadOnly.java:168)
	at us.ihmc.euclid.geometry.interfaces.ConvexPolygon2DBasics.addVertices(ConvexPolygon2DBasics.java:183)
	at us.ihmc.euclid.geometry.interfaces.ConvexPolygon2DBasics.set(ConvexPolygon2DBasics.java:237)
	at us.ihmc.euclid.geometry.ConvexPolygon2D.<init>(ConvexPolygon2D.java:117)
```

**Comment by SylvainBertrand** [comment]
@Richiedu38 let's create a unit-test for this issue
